#!/usr/bin/env node
/**
 * Orchestrator: takes an episode → ensures every newBoundElement has its
 * local PNG generated by Nano Banana → triggers uploadElements.mjs to
 * upload + create the named element in Kling's library.
 *
 *   ep<NN>.json.newBoundElements
 *      ├─ for each: PNG exists locally?
 *      │    yes → skip gen
 *      │    no  → python3 generateScenes.py --scene <stem>   (scenes)
 *      │      OR python3 generateProps.py  --prop  <stem>    (props)
 *      │           then cp <stem>_v1.png <stem>.png          (auto-pick v1)
 *      └─ all PNGs ready → spawn uploadElements.mjs with manifest
 *
 * Scene vs prop is decided from the boundElement.purpose (or explicit `kind`
 * field) — anything mentioning room/scene/interior is a scene, else a prop.
 *
 * Prereqs:
 *   - Chrome at debug port 9222 with logged-in Kling tab (for upload phase)
 *   - GEMINI_API_KEY in .env.local (for generation phase)
 *   - generateScenes.py / generateProps.py have the tag's stem in their dict
 *
 * Usage:
 *   node ensureElements.mjs <path/to/episode.json>
 *   node ensureElements.mjs --episode=8                   # resolves content/episodes/ep08.json
 *   node ensureElements.mjs <input> --pick=2              # use _v2 for props instead of _v1
 *   node ensureElements.mjs <input> --skip-upload         # gen only, no Kling
 *   node ensureElements.mjs <input> --skip-gen            # upload only, no Nano Banana
 *   node ensureElements.mjs <input> --dry-run             # plan only
 */
import path from "node:path";
import fs from "node:fs";
import { spawnSync } from "node:child_process";

const PROJECT_ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), "../../../..");

// ─── Args ───────────────────────────────────────────────────────────────────
const argv = process.argv.slice(2);
const flags = Object.fromEntries(
  argv.filter(a => a.startsWith("--")).map(a => {
    const [k, v] = a.replace(/^--/, "").split("=");
    return [k, v ?? "true"];
  })
);
const positional = argv.filter(a => !a.startsWith("--"));

const pick = Number(flags.pick ?? 1);
const dryRun = flags["dry-run"] === "true";
const skipGen = flags["skip-gen"] === "true";
const skipUpload = flags["skip-upload"] === "true";

let epPath;
if (positional[0]) {
  epPath = path.resolve(positional[0]);
} else if (flags.episode) {
  epPath = path.join(PROJECT_ROOT, "content", "episodes", `ep${String(flags.episode).padStart(2, "0")}.json`);
} else {
  console.error("Usage: node ensureElements.mjs <episode.json> | --episode=<NN>  [--pick=N] [--skip-upload] [--skip-gen] [--dry-run]");
  process.exit(1);
}

if (!fs.existsSync(epPath)) {
  console.error(`❌ episode JSON not found: ${epPath}`);
  process.exit(1);
}
const ep = JSON.parse(fs.readFileSync(epPath, "utf8"));
const episode = ep.episode ?? flags.episode ?? path.basename(epPath, ".json").replace(/^ep0?/, "");
const newElements = ep.newBoundElements ?? [];
if (newElements.length === 0) {
  console.log(`ℹ️  ${path.basename(epPath)} has no newBoundElements — nothing to do.`);
  process.exit(0);
}

// ─── Plan ───────────────────────────────────────────────────────────────────
const items = newElements.map(e => {
  const assetPath = path.isAbsolute(e.asset) ? e.asset : path.join(PROJECT_ROOT, e.asset);
  const stem = path.basename(assetPath, path.extname(assetPath));
  const kind = e.kind ?? (/scene|room|interior|backdrop|background/i.test(e.purpose ?? "") ? "scene" : "prop");
  return { tag: e.tag, assetPath, stem, kind, exists: fs.existsSync(assetPath) };
});

console.log(`\n📋 ep${String(episode).padStart(2, "0")} newBoundElements (${items.length}):`);
for (const it of items) {
  const status = it.exists ? "✓ PNG exists" : "✗ MISSING — needs gen";
  console.log(`   [${it.kind.padEnd(5)}] @${it.tag.padEnd(24)} ${status}`);
  console.log(`           ${path.relative(PROJECT_ROOT, it.assetPath)}`);
}

const toGenerate = items.filter(it => !it.exists);
const allReady = toGenerate.length === 0;

console.log(`\n→ ${toGenerate.length} need generating, ${items.length - toGenerate.length} already have PNGs`);

if (dryRun) {
  console.log(`\n[dry-run] would gen: ${toGenerate.map(t => t.stem).join(", ") || "(none)"}`);
  console.log(`[dry-run] would upload via uploadElements.mjs ${path.relative(PROJECT_ROOT, epPath)}`);
  process.exit(0);
}

// ─── Phase 1: Generate missing PNGs ─────────────────────────────────────────
if (!skipGen && toGenerate.length > 0) {
  console.log(`\n🎨 Phase 1: Nano Banana generation`);
  const sceneGenerator = path.join(PROJECT_ROOT, "content", "generateScenes.py");
  const propGenerator  = path.join(PROJECT_ROOT, "content", "generateProps.py");

  for (const it of toGenerate) {
    console.log(`\n   ▶ generating ${it.kind}: ${it.stem}`);
    const script = it.kind === "scene" ? sceneGenerator : propGenerator;
    const flagName = it.kind === "scene" ? "--scene" : "--prop";
    const res = spawnSync("python3", [script, flagName, it.stem], { stdio: "inherit", cwd: PROJECT_ROOT });
    if (res.status !== 0) {
      console.error(`   ❌ ${path.basename(script)} exited ${res.status} for ${it.stem}`);
      console.error(`   Hint: make sure "${it.stem}" is registered in ${path.basename(script)}'s catalog dict.`);
      process.exit(1);
    }

    // Props produce <stem>_v1.png, _v2.png, _v3.png — pick one
    if (it.kind === "prop" && !fs.existsSync(it.assetPath)) {
      const variantPath = path.join(path.dirname(it.assetPath), `${it.stem}_v${pick}.png`);
      if (!fs.existsSync(variantPath)) {
        console.error(`   ❌ expected variant ${path.basename(variantPath)} not found after gen.`);
        const dir = path.dirname(it.assetPath);
        const variants = fs.readdirSync(dir).filter(f => f.startsWith(`${it.stem}_v`));
        console.error(`      Available: ${variants.join(", ") || "(none)"}`);
        process.exit(1);
      }
      fs.copyFileSync(variantPath, it.assetPath);
      console.log(`   ✓ picked v${pick} → ${path.basename(it.assetPath)}`);
    }

    if (!fs.existsSync(it.assetPath)) {
      console.error(`   ❌ generation completed but ${path.basename(it.assetPath)} still missing.`);
      process.exit(1);
    }
    it.exists = true;
  }
} else if (skipGen) {
  console.log(`\n⏭  skipping gen phase (--skip-gen)`);
}

// ─── Phase 2: Upload via uploadElements.mjs ─────────────────────────────────
if (skipUpload) {
  console.log(`\n⏭  skipping upload phase (--skip-upload)`);
  console.log(`\n✅ all PNGs ready under assets/scenes/`);
  process.exit(0);
}

const stillMissing = items.filter(it => !fs.existsSync(it.assetPath));
if (stillMissing.length > 0) {
  console.error(`\n❌ cannot upload — ${stillMissing.length} PNG(s) still missing:`);
  for (const m of stillMissing) console.error(`   - ${m.stem}`);
  process.exit(1);
}

console.log(`\n📤 Phase 2: upload to Kling library`);
const uploadScript = path.join(PROJECT_ROOT, ".claude", "skills", "saraandeva-episode", "scripts", "uploadElements.mjs");
const res = spawnSync("node", [uploadScript, epPath], { stdio: "inherit", cwd: PROJECT_ROOT });
process.exit(res.status ?? 1);
