#!/usr/bin/env python3
"""Validate a Nano-Banana render (or any image) for anatomical / pose defects.

Uses gemini-2.5-flash vision to detect:
  - 180° head rotation (head facing one way, body facing the other)
  - Extra arms / hands / fingers
  - Missing limbs
  - Faces facing camera while body is facing away (or vice-versa)
  - Merged characters (two characters fused into one)
  - Floating limbs (limbs detached from body)
  - Wrong eye count / asymmetric eyes
  - Distorted faces / horror-uncanny features

User-driven 2026-05-11: ep16 clip 15 start_v2 had Eva's head visible from front
while body was facing the couch (rear-facing). Per "validation should be in
the pipeline", this script automates the catch.

Usage:
    # Single image
    python3 validate_nano_render.py path/to/image.png

    # Multiple images (returns sorted pass-list)
    python3 validate_nano_render.py img1.png img2.png img3.png

    # Folder
    python3 validate_nano_render.py --folder content/episodes/ep16/_test_nano/pair_A_approach_reveal/candidates/

    # Strict mode (any flag = fail), JSON output
    python3 validate_nano_render.py --strict --json img.png

Exit codes: 0 = all images clean | 1 = at least one image flagged
"""
from __future__ import annotations
import argparse
import base64
import json
import os
import re
import sys
import time
import urllib.request
import urllib.error
from pathlib import Path

ROOT = Path("/Volumes/Samsung500/goreadling-production")
ENV_FILE = ROOT / ".env.local"
MODEL = "gemini-2.5-flash"
API_BASE = "https://generativelanguage.googleapis.com/v1beta/models"


def load_env(path: Path) -> None:
    if not path.exists():
        return
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        k = k.strip()
        v = v.strip().strip('"').strip("'")
        if k and k not in os.environ:
            os.environ[k] = v


def get_api_keys() -> list[str]:
    load_env(ENV_FILE)
    out = []
    for name in ("GEMINI_API_KEY", "GEMINI_API_KEY_2", "GEMINI_API_KEY_3",
                 "GEMINI_API_KEY_4", "GEMINI_API_KEY_5", "GEMINI_API_KEY_6"):
        v = os.environ.get(name)
        if v:
            out.append(v.replace('"', "").strip())
    return out


def load_inline(path: Path) -> dict:
    ext = path.suffix.lower()
    mime = {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
            ".webp": "image/webp"}.get(ext, "image/jpeg")
    return {"inlineData": {"mimeType": mime,
                            "data": base64.b64encode(path.read_bytes()).decode("ascii")}}


PROMPT_HEADER = """You are an anatomy, pose, and continuity checker for animated children's-show character renders. The image you see was generated by Nano-Banana (Gemini 3 Pro Image) and may contain anatomical impossibilities, pose inconsistencies, OR character-count / context defects that need to be caught BEFORE the render is used downstream.

Inspect the image and check for each of these defects. Be STRICT and SUSPICIOUS — false negatives (missing a real defect) are worse than false positives.

{spec_block}

Defects to detect:

1. **head_body_rotation_mismatch**: A character's head/face is rotated significantly more than possible relative to their body. SPECIFIC CHECKS:
   (a) If the character's chest/torso/shoulders point AWAY from camera (you'd see their back), then their face should NOT be fully visible from the front. A face seen straight-on while shoulders show the back is anatomically impossible (>120° neck twist).
   (b) If the character's body is in a posture suggesting they are facing AWAY (e.g., reaching FORWARD into something, leaning OVER a barrier in front of them, gripping something positioned ahead of their torso), but their face is shown facing the camera, this is a rotation mismatch.
   (c) Even subtle cases: if hands/arms suggest the character is gripping or reaching something to their REAR (behind body), but the face is camera-facing, the body must have been depicted facing AWAY — flag it.
   (d) Verify by checking 3 anchors: shoulder direction, hip/torso facing, foot direction. ALL must plausibly match the head facing.

2. **extra_limbs**: A character has more than 2 arms, more than 2 legs, more than 1 head, or more than 2 hands visible (excluding overlap with another character).

3. **missing_limbs**: A character is missing an arm/leg/hand where it should anatomically be visible.

4. **floating_limb**: A limb appears to float, detached from the body it should be connected to.

5. **merged_characters**: Two characters appear fused (shared head, shared torso, fused outline).

6. **face_distortion**: A face has anatomical errors (wrong number of eyes, asymmetric eye height by more than ~20%, asymmetric mouth, eyes melting/glitching, distorted features).

7. **finger_anomaly**: A hand has wrong number of fingers, fused fingers, or distorted fingers.

8. **horror_uncanny**: Anything that reads as "uncanny" or unsettling for a children's show — scary face, soulless eyes, weird grin, blank expression in a wrong context.

9. **duplicate_character**: TWO (or more) of the SAME character visible in the scene when only one was specified. Example: two of the same dog, two of the same toddler, two of the same adult woman. Includes ghost spawns at the edges of the frame, mirror reflections (unless an actual mirror is in scene), and "echo" duplicates near doors, in corners, or in the background. CRITICAL CHECK: if you see what appears to be the same character TWICE (matching breed, matching hair color, matching outfit, matching face), flag this even if one is partially out of frame or visually de-emphasized. Cross-reference against the EXPECTED SUBJECTS list above — if a subject is named only once, there must be exactly ONE of them visible.

10. **unexpected_extra_character**: A character appears in the scene who is NOT in the expected subjects list. Examples: a stranger child, an unknown adult, an unexpected pet, an extra family member. Even silhouettes, partial figures, or background-blur figures count.

11. **context_anomaly**: The character's state contradicts the scene context. Examples: a character is asleep in bed but wearing outdoor shoes; a character is eating but has no food in hand; a character is shown brushing teeth but no toothbrush visible; nighttime scene but character has full-day-makeup look. Use the CONTEXT NOTE above (if provided) as ground truth for what state/situation the character should be in.

Respond with STRICT JSON, no markdown fences:

{
  "anatomical_pass": true | false,
  "visible_character_count": <integer — total number of distinct characters (people + animals) you can see, including ghosts/duplicates>,
  "expected_character_count": <integer — what the spec says should be visible, or -1 if not provided>,
  "defects": [
    {"type": "<defect_type_from_list_above>", "severity": "high" | "medium" | "low", "subject": "<which character: name or position>", "notes": "<one short sentence>"}
  ],
  "overall_quality": "clean" | "minor_issues" | "rejected",
  "recommendation": "use" | "reuse_with_caveats" | "re-render",
  "summary": "<one sentence overall assessment>"
}

Be HONEST. If you see ANY of the listed defects, set anatomical_pass=false. If the image is clean, set defects=[] and anatomical_pass=true. If `visible_character_count` does NOT match `expected_character_count`, that itself is a defect (use `duplicate_character` or `unexpected_extra_character` as appropriate). Answer ONLY with the JSON object."""


def build_prompt(subjects: list[str] | None = None, context: str | None = None) -> str:
    """Build the full prompt with optional subjects + context spec block."""
    spec_lines = []
    if subjects:
        spec_lines.append(f"EXPECTED SUBJECTS: exactly {len(subjects)} character(s) "
                          f"should be visible: {', '.join(subjects)}. NO extra "
                          f"characters, NO duplicates of any subject.")
    if context:
        spec_lines.append(f"CONTEXT NOTE: {context}")
    spec_block = "\n".join(spec_lines) if spec_lines else "(no spec provided — be especially suspicious of duplicates and extras)"
    # Use .replace() not .format() — the prompt contains literal JSON braces.
    return PROMPT_HEADER.replace("{spec_block}", spec_block)


def call_gemini(image: Path, keys: list[str], retries: int = 4,
                 subjects: list[str] | None = None,
                 context: str | None = None) -> dict:
    prompt = build_prompt(subjects, context)
    parts = [load_inline(image), {"text": prompt}]
    body = {
        "contents": [{"parts": parts}],
        "generationConfig": {"temperature": 0.1, "responseMimeType": "application/json"},
    }
    data = json.dumps(body).encode("utf-8")

    for attempt in range(retries):
        key = keys[attempt % len(keys)]
        url = f"{API_BASE}/{MODEL}:generateContent?key={key}"
        req = urllib.request.Request(url, data=data,
                                      headers={"Content-Type": "application/json"},
                                      method="POST")
        try:
            with urllib.request.urlopen(req, timeout=90) as resp:
                rj = json.loads(resp.read())
        except urllib.error.HTTPError as e:
            if e.code == 429:
                time.sleep(20)
                continue
            return {"error": f"HTTP {e.code}: {e.read()[:200]}"}
        except Exception as e:
            return {"error": f"{type(e).__name__}: {e}"}

        text = ""
        for cand in rj.get("candidates", []):
            for p in (cand.get("content") or {}).get("parts") or []:
                if p.get("text"):
                    text += p["text"]
        text = re.sub(r"^```(?:json)?\s*|\s*```$", "", text.strip(), flags=re.DOTALL)
        try:
            return json.loads(text)
        except Exception:
            time.sleep(2)
            continue
    return {"error": "all attempts failed"}


def format_finding(image: Path, result: dict, json_mode: bool) -> str:
    if json_mode:
        return json.dumps({"image": str(image), **result})

    if "error" in result:
        return f"❌ {image.name}  API ERROR: {result['error']}"

    passes = result.get("anatomical_pass", False)
    quality = result.get("overall_quality", "?")
    rec = result.get("recommendation", "?")
    defects = result.get("defects", [])

    icon = "✅" if passes else "🔴"
    head = f"{icon} {image.name}  {quality.upper():<13} → {rec}"
    if not defects:
        return head + f"\n     {result.get('summary', '')}"
    lines = [head]
    for d in defects:
        sev = d.get("severity", "?")
        sev_icon = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(sev, "  ")
        lines.append(f"     {sev_icon} {d.get('type')} on {d.get('subject', '?')}: "
                     f"{d.get('notes', '')}")
    lines.append(f"     ➜ {result.get('summary', '')}")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("images", nargs="*", help="Image files to check")
    ap.add_argument("--folder", help="Validate all images in folder")
    ap.add_argument("--strict", action="store_true",
                    help="Exit 1 on any non-pass (default: exit 1 only if recommendation=re-render)")
    ap.add_argument("--json", action="store_true", help="Output one JSON line per image")
    ap.add_argument("--subjects", default=None,
                    help="Comma-separated list of expected subjects in the image "
                         "(e.g. 'Eva,Joe'). Used to detect duplicates + extras.")
    ap.add_argument("--context", default=None,
                    help="Free-text scene context note (e.g. 'bedroom night, Eva "
                         "sleeping under covers'). Used to detect context anomalies.")
    args = ap.parse_args()
    subjects_list = [s.strip() for s in args.subjects.split(",")] if args.subjects else None

    targets: list[Path] = []
    if args.folder:
        for p in sorted(Path(args.folder).iterdir()):
            if p.suffix.lower() in {".png", ".jpg", ".jpeg", ".webp"}:
                targets.append(p)
    for s in args.images:
        targets.append(Path(s))

    if not targets:
        sys.exit("❌ no images specified (use positional args or --folder)")

    keys = get_api_keys()
    if not keys:
        sys.exit("❌ no GEMINI_API_KEY* in env or .env.local")

    if not args.json:
        print(f"━━━ validating {len(targets)} image(s) via {MODEL} ━━━\n")

    pass_count = 0
    rejected = 0
    for img in targets:
        if not img.is_file():
            print(f"⚠️  skip (not found): {img}")
            continue
        result = call_gemini(img, keys, subjects=subjects_list, context=args.context)
        line = format_finding(img, result, args.json)
        print(line)

        if "error" in result:
            continue
        rec = result.get("recommendation", "re-render")
        if rec == "use":
            pass_count += 1
        if rec == "re-render":
            rejected += 1

    if not args.json:
        print(f"\n━━━ {pass_count} clean / {len(targets) - pass_count - rejected} caveats / {rejected} rejected ━━━")

    if args.strict and pass_count < len(targets):
        sys.exit(1)
    if rejected > 0:
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
